### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by eelke** [osiloke/ofxLayout#1]
The repo misses a couple of required files, such as "actionListener.h" and "actionEvent.h", and cannot be compiled. Can you please download the repo as you have published it here, and see what is missing? Thanks!

**Comment by osiloke** [comment]
Hi, thanks for checking out the repo. I have removed the dependence on ofxAction you can pull the master and it should work. 
ofxAction is supposed to enable you to perform an action when a namespaced property is changed. You can specify an ofxAction in the layout file (but its not ready yet).
Thanks

**Comment by osiloke** [comment]
I just noticed that i had mixed up some commits, i'm fixing the repo and i'll update this issue soon

**Comment by osiloke** [comment]
The current revision, 160ddb3db730eb9de1e199a4468162f1943b9c20, should be fixed

**Comment by osiloke** [comment]
So i just recently resumed work on this library and will be pushing much more updates, fixing bugs etc
